### PR TITLE
Solve error typing 0.

### LINKED ISSUE #10: Error typing 0.
When type 0., the app crash on eval it with `Number.toLocaleString()`.

### PR DESCRIPTION
**Pull request by dpuentel**
Fix #10.

Prevent eval `0.` with `Number.toLocaleString()`.

Show `ERROR!` on display if the result is `NaN`.

Fix `.editorconfig` setting `indent_style = space` to follow the standardjs guidelines.

### CODE REVIEW

File: js/index.js [hunk 1]
```diff
@@ -125,10 +127,20 @@ const getScreenValue = () => {
 }
 
 const updateScreen = () => {
+  console.log(currentOperation)
```
Comment (halivert) [inline js/index.js]: Please remove this console.log

**Review by halivert — CHANGES_REQUESTED** [review]
Seems nice, but need to delete a line

**Review by halivert — APPROVED** [review]
